/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import java.awt.Color;

/**
 *
 * @author RIGISEFA
 */
public class Beranda extends javax.swing.JFrame {

    /**
     * Creates new form Beranda
     */
    public Beranda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pkiri = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Bberanda = new javax.swing.JPanel();
        Btnberanda = new javax.swing.JLabel();
        Tberanda = new javax.swing.JPanel();
        Bbuku = new javax.swing.JPanel();
        Tbuku = new javax.swing.JPanel();
        Btnbuku = new javax.swing.JLabel();
        Bskripsi = new javax.swing.JPanel();
        Tskripsi = new javax.swing.JPanel();
        Btnskripsi = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pkanan = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Pnutama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pkiri.setBackground(new java.awt.Color(204, 102, 0));
        pkiri.setPreferredSize(new java.awt.Dimension(250, 517));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gudang Berkas");

        Bberanda.setBackground(new java.awt.Color(204, 102, 0));
        Bberanda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        Btnberanda.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Btnberanda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Btnberanda.setText("Beranda");
        Btnberanda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnberandaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnBtnberandaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnBtnberandaMouseExited(evt);
            }
        });

        Tberanda.setBackground(new java.awt.Color(204, 102, 0));

        javax.swing.GroupLayout TberandaLayout = new javax.swing.GroupLayout(Tberanda);
        Tberanda.setLayout(TberandaLayout);
        TberandaLayout.setHorizontalGroup(
            TberandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        TberandaLayout.setVerticalGroup(
            TberandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout BberandaLayout = new javax.swing.GroupLayout(Bberanda);
        Bberanda.setLayout(BberandaLayout);
        BberandaLayout.setHorizontalGroup(
            BberandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BberandaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Tberanda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btnberanda, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        BberandaLayout.setVerticalGroup(
            BberandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BberandaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Tberanda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(Btnberanda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Bbuku.setBackground(new java.awt.Color(204, 102, 0));
        Bbuku.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        Tbuku.setBackground(new java.awt.Color(204, 102, 0));

        javax.swing.GroupLayout TbukuLayout = new javax.swing.GroupLayout(Tbuku);
        Tbuku.setLayout(TbukuLayout);
        TbukuLayout.setHorizontalGroup(
            TbukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        TbukuLayout.setVerticalGroup(
            TbukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        Btnbuku.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Btnbuku.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Btnbuku.setText("Buku");
        Btnbuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnbukuMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnbukuMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnbukuMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout BbukuLayout = new javax.swing.GroupLayout(Bbuku);
        Bbuku.setLayout(BbukuLayout);
        BbukuLayout.setHorizontalGroup(
            BbukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BbukuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tbuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btnbuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BbukuLayout.setVerticalGroup(
            BbukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BbukuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tbuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(Btnbuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Bskripsi.setBackground(new java.awt.Color(204, 102, 0));
        Bskripsi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        Tskripsi.setBackground(new java.awt.Color(204, 102, 0));

        javax.swing.GroupLayout TskripsiLayout = new javax.swing.GroupLayout(Tskripsi);
        Tskripsi.setLayout(TskripsiLayout);
        TskripsiLayout.setHorizontalGroup(
            TskripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        TskripsiLayout.setVerticalGroup(
            TskripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        Btnskripsi.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Btnskripsi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Btnskripsi.setText("Skripsi");
        Btnskripsi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnskripsiMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnskripsiMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnskripsiMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout BskripsiLayout = new javax.swing.GroupLayout(Bskripsi);
        Bskripsi.setLayout(BskripsiLayout);
        BskripsiLayout.setHorizontalGroup(
            BskripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BskripsiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btnskripsi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BskripsiLayout.setVerticalGroup(
            BskripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BskripsiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(Btnskripsi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("MENU");

        javax.swing.GroupLayout pkiriLayout = new javax.swing.GroupLayout(pkiri);
        pkiri.setLayout(pkiriLayout);
        pkiriLayout.setHorizontalGroup(
            pkiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pkiriLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(pkiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pkiriLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pkiriLayout.createSequentialGroup()
                        .addGroup(pkiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Bskripsi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Bbuku, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pkiriLayout.createSequentialGroup()
                                .addComponent(Bberanda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(13, 13, 13))))
        );
        pkiriLayout.setVerticalGroup(
            pkiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pkiriLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bberanda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Bbuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Bskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(216, 216, 216))
        );

        getContentPane().add(pkiri, java.awt.BorderLayout.LINE_START);

        pkanan.setBackground(new java.awt.Color(153, 51, 0));
        pkanan.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(204, 51, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 777, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        pkanan.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(153, 51, 0));

        Pnutama.setBackground(new java.awt.Color(153, 102, 0));
        Pnutama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Pnutama.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(Pnutama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Pnutama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        pkanan.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(pkanan, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBtnberandaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnBtnberandaMouseEntered
        Bberanda.setBackground(new Color(153,102,0));
        Tberanda.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_BtnBtnberandaMouseEntered

    private void BtnBtnberandaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnBtnberandaMouseExited
        Bberanda.setBackground(new Color(204,102,0));
        Tberanda.setBackground(new Color(204,102,0));
    }//GEN-LAST:event_BtnBtnberandaMouseExited

    private void BtnbukuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnbukuMouseEntered
        Bbuku.setBackground(new Color(153,102,0));
        Tbuku.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_BtnbukuMouseEntered

    private void BtnbukuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnbukuMouseExited
        Bbuku.setBackground(new Color(204,102,0));
        Tbuku.setBackground(new Color(204,102,0));
    }//GEN-LAST:event_BtnbukuMouseExited

    private void BtnskripsiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnskripsiMouseExited
        Bskripsi.setBackground(new Color(204,102,0));
        Tskripsi.setBackground(new Color(204,102,0));
    }//GEN-LAST:event_BtnskripsiMouseExited

    private void BtnskripsiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnskripsiMouseEntered
        Bskripsi.setBackground(new Color(153,102,0));
        Tskripsi.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_BtnskripsiMouseEntered

    private void BtnberandaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnberandaMouseClicked
        Bberanda.setBackground(new Color(143,92,0));
        Tberanda.setBackground(new Color(0,0,0));
        
        Pnutama.removeAll();
        Pnutama.add(new Info());
        Pnutama.repaint();
        Pnutama.revalidate();
    }//GEN-LAST:event_BtnberandaMouseClicked

    private void BtnbukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnbukuMouseClicked
        Bbuku.setBackground(new Color(143,92,0));
        Tbuku.setBackground(new Color(0,0,0));
        
        Pnutama.removeAll();
        Pnutama.add(new BukuP(Pnutama));
        Pnutama.repaint();
        Pnutama.revalidate();
    }//GEN-LAST:event_BtnbukuMouseClicked

    private void BtnskripsiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnskripsiMouseClicked
        Bskripsi.setBackground(new Color(143,92,0));
        Tskripsi.setBackground(new Color(0,0,0));
        
        Pnutama.removeAll();
        Pnutama.add(new SkripsiP(Pnutama));
        Pnutama.repaint();
        Pnutama.revalidate();
    }//GEN-LAST:event_BtnskripsiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Beranda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bberanda;
    private javax.swing.JPanel Bbuku;
    private javax.swing.JPanel Bskripsi;
    private javax.swing.JLabel Btnberanda;
    private javax.swing.JLabel Btnbuku;
    private javax.swing.JLabel Btnskripsi;
    private javax.swing.JPanel Pnutama;
    private javax.swing.JPanel Tberanda;
    private javax.swing.JPanel Tbuku;
    private javax.swing.JPanel Tskripsi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pkanan;
    private javax.swing.JPanel pkiri;
    // End of variables declaration//GEN-END:variables

}
